package com.example.coderqiang.xmatch_android.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.coderqiang.xmatch_android.model.AppNotice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_NOTICE".
*/
public class AppNoticeDao extends AbstractDao<AppNotice, Long> {

    public static final String TABLENAME = "APP_NOTICE";

    /**
     * Properties of entity AppNotice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AppNoticeId = new Property(0, Long.class, "appNoticeId", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property CreateTime = new Property(3, long.class, "createTime", false, "CREATE_TIME");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property DepartmentId = new Property(5, long.class, "departmentId", false, "DEPARTMENT_ID");
    }


    public AppNoticeDao(DaoConfig config) {
        super(config);
    }
    
    public AppNoticeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_NOTICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: appNoticeId
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT\" TEXT," + // 2: content
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 3: createTime
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"DEPARTMENT_ID\" INTEGER NOT NULL );"); // 5: departmentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_NOTICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppNotice entity) {
        stmt.clearBindings();
 
        Long appNoticeId = entity.getAppNoticeId();
        if (appNoticeId != null) {
            stmt.bindLong(1, appNoticeId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getCreateTime());
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getDepartmentId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppNotice entity) {
        stmt.clearBindings();
 
        Long appNoticeId = entity.getAppNoticeId();
        if (appNoticeId != null) {
            stmt.bindLong(1, appNoticeId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getCreateTime());
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getDepartmentId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AppNotice readEntity(Cursor cursor, int offset) {
        AppNotice entity = new AppNotice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // appNoticeId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getLong(offset + 3), // createTime
            cursor.getInt(offset + 4), // type
            cursor.getLong(offset + 5) // departmentId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppNotice entity, int offset) {
        entity.setAppNoticeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateTime(cursor.getLong(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setDepartmentId(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppNotice entity, long rowId) {
        entity.setAppNoticeId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppNotice entity) {
        if(entity != null) {
            return entity.getAppNoticeId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AppNotice entity) {
        return entity.getAppNoticeId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
