package com.example.coderqiang.xmatch_android.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.coderqiang.xmatch_android.model.ActivityApply;
import com.example.coderqiang.xmatch_android.model.AppNotice;
import com.example.coderqiang.xmatch_android.model.Attendance;
import com.example.coderqiang.xmatch_android.model.ChildDepartment;
import com.example.coderqiang.xmatch_android.model.Course;
import com.example.coderqiang.xmatch_android.model.Department;
import com.example.coderqiang.xmatch_android.model.DepManager;
import com.example.coderqiang.xmatch_android.model.EmailNotice;
import com.example.coderqiang.xmatch_android.model.Message;
import com.example.coderqiang.xmatch_android.model.User;

import com.example.coderqiang.xmatch_android.dao.ActivityApplyDao;
import com.example.coderqiang.xmatch_android.dao.AppNoticeDao;
import com.example.coderqiang.xmatch_android.dao.AttendanceDao;
import com.example.coderqiang.xmatch_android.dao.ChildDepartmentDao;
import com.example.coderqiang.xmatch_android.dao.CourseDao;
import com.example.coderqiang.xmatch_android.dao.DepartmentDao;
import com.example.coderqiang.xmatch_android.dao.DepManagerDao;
import com.example.coderqiang.xmatch_android.dao.EmailNoticeDao;
import com.example.coderqiang.xmatch_android.dao.MessageDao;
import com.example.coderqiang.xmatch_android.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activityApplyDaoConfig;
    private final DaoConfig appNoticeDaoConfig;
    private final DaoConfig attendanceDaoConfig;
    private final DaoConfig childDepartmentDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig departmentDaoConfig;
    private final DaoConfig depManagerDaoConfig;
    private final DaoConfig emailNoticeDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ActivityApplyDao activityApplyDao;
    private final AppNoticeDao appNoticeDao;
    private final AttendanceDao attendanceDao;
    private final ChildDepartmentDao childDepartmentDao;
    private final CourseDao courseDao;
    private final DepartmentDao departmentDao;
    private final DepManagerDao depManagerDao;
    private final EmailNoticeDao emailNoticeDao;
    private final MessageDao messageDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        activityApplyDaoConfig = daoConfigMap.get(ActivityApplyDao.class).clone();
        activityApplyDaoConfig.initIdentityScope(type);

        appNoticeDaoConfig = daoConfigMap.get(AppNoticeDao.class).clone();
        appNoticeDaoConfig.initIdentityScope(type);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        childDepartmentDaoConfig = daoConfigMap.get(ChildDepartmentDao.class).clone();
        childDepartmentDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        depManagerDaoConfig = daoConfigMap.get(DepManagerDao.class).clone();
        depManagerDaoConfig.initIdentityScope(type);

        emailNoticeDaoConfig = daoConfigMap.get(EmailNoticeDao.class).clone();
        emailNoticeDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        activityApplyDao = new ActivityApplyDao(activityApplyDaoConfig, this);
        appNoticeDao = new AppNoticeDao(appNoticeDaoConfig, this);
        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);
        childDepartmentDao = new ChildDepartmentDao(childDepartmentDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        depManagerDao = new DepManagerDao(depManagerDaoConfig, this);
        emailNoticeDao = new EmailNoticeDao(emailNoticeDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ActivityApply.class, activityApplyDao);
        registerDao(AppNotice.class, appNoticeDao);
        registerDao(Attendance.class, attendanceDao);
        registerDao(ChildDepartment.class, childDepartmentDao);
        registerDao(Course.class, courseDao);
        registerDao(Department.class, departmentDao);
        registerDao(DepManager.class, depManagerDao);
        registerDao(EmailNotice.class, emailNoticeDao);
        registerDao(Message.class, messageDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        activityApplyDaoConfig.clearIdentityScope();
        appNoticeDaoConfig.clearIdentityScope();
        attendanceDaoConfig.clearIdentityScope();
        childDepartmentDaoConfig.clearIdentityScope();
        courseDaoConfig.clearIdentityScope();
        departmentDaoConfig.clearIdentityScope();
        depManagerDaoConfig.clearIdentityScope();
        emailNoticeDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ActivityApplyDao getActivityApplyDao() {
        return activityApplyDao;
    }

    public AppNoticeDao getAppNoticeDao() {
        return appNoticeDao;
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

    public ChildDepartmentDao getChildDepartmentDao() {
        return childDepartmentDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public DepManagerDao getDepManagerDao() {
        return depManagerDao;
    }

    public EmailNoticeDao getEmailNoticeDao() {
        return emailNoticeDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
